Add responsive size
dbetka/vue-material-symbols pull request #1
Opened 2024-08-23 14:12 UTC by Tatayoyoh

Hi @dbetka !
I would like to contribute to your great package by adding responsive size like '2.5em' or '250%'.

Value can be passed as app project configuration
```
import materialSymbolsPlugin from '@dbetka/vue-material-symbols';
import 'material-symbols/index.css';

const app = createApp(App);
app.use(materialSymbolsPlugin, {
  defaultSize: '1.5em',
});
```

or attribute
```
<MaterialSymbol name="delete" size="1.5em">
<MaterialSymbol name="delete" size="150%">
```

Can you validate this evolution and release a new package version if ok ?
Thanks a lot for your code :)

2024-08-25 16:49 UTC, dbetka commented
Hi @Tatayoyoh,
Thanks for your commitment!

This is a great idea and I will look at it tonight or tomorrow morning. 🙂

2024-08-26 08:08 UTC, dbetka requested changes
Idea looks good and it seems to work after small corrections.
I think we should add some relative value to `demo/DemoComponent.vue`.

For example change this
```js
const sizes = [ undefined, 40, 56, 72, 96, 128 ]
```
to this
```js
const sizes = [ undefined, 40, 56, 72, 96, '7.5rem' ]
```

Are you able to make this modifications? 
After that I will release a new package version.

2024-08-26 08:08 UTC, dbetka commented on src/MaterialSymbol.vue
> +  const opsz = Number.isIntefer(props.size) ? props.size : window.$materialSymbolsDefaults?.defaultSize || DEFAULT_SIZE,
```suggestion
  const size = Number.isInteger(props.size) ? `${props.size}px` : props.size
  const opsz = Number.isInteger(props.size) ? props.size : window.$materialSymbolsDefaults?.defaultSize || DEFAULT_SIZE
```

2024-08-26 12:40 UTC, Tatayoyoh commented
Hey, I fixed two ugly code errors from my previous pull request and added the example into `demo/DemoComponent.vue` like you said. I can see conflicts now, sorry I have not seen you made changes :open_mouth:

2024-08-28 08:14 UTC, dbetka approved these changes
PR is ready to merge and release today - Thank you for your commitment :)

2024-08-28 08:14 UTC, dbetka commented on demo/DemoComponent.vue
> +const sizes = [ undefined, 40, 56, 72, 96, "7.5em" ]
Single quote is preferable by eslint but I will change it right before release.

2024-08-28 08:15 UTC, merged

2024-08-28 08:22 UTC, dbetka commented
@Tatayoyoh new version has been released 🚀 
Check if everything works fine

2024-09-02 13:44 UTC, Tatayoyoh commented
Thank you a lot for this ! :1st_place_medal: